# Generated by Django 4.2.16 on 2026-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена до скидки. Если задана и больше текущей — товар на распродаже.', max_digits=12, null=True),
        ),
    ]
