# Generated by Django 4.2.16 on 2026-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Подпись под видео (необязательно).', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='YouTube / Rutube / VK ссылка на видео.')),
                ('video_file', models.FileField(blank=True, help_text='Видео-файл (mp4). Используется, если ссылка пустая.', null=True, upload_to='homepage_videos/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Свой превью-кадр. Если пусто — берётся автоматически для YouTube.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше — тем выше в ленте.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео-обзор (главная)',
                'verbose_name_plural': 'Видео-обзоры (главная)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Видео-файл (mp4). Используется, если ссылка пустая.', null=True, upload_to='product_videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео-обзор (YouTube embed или прямая ссылка на .mp4).'),
        ),
    ]
