# Generated by Django 4.2.16 on 2026-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_videoreview_product_video_file_product_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.FileField(blank=True, help_text='Файл-логотип (SVG/PNG/JPG). Если задан, перебивает logo_url.', null=True, upload_to='brand_logos/')),
                ('logo_url', models.URLField(blank=True, help_text='URL логотипа (используется, если файл не загружен).')),
                ('website', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=True, help_text='Показывать в слайдере брендов на главной.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['order', 'name'],
            },
        ),
    ]
