# Generated by Django 4.2.16 on 2026-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_blocked',
            field=models.BooleanField(default=False, help_text='True если YouTube/Rutube запретил встраивание (Error 153). Такие видео отправляем в конец списка.'),
        ),
    ]
